
running 1 test
test fmm::test::test_fmm_vector ... FAILED

failures:

---- fmm::test::test_fmm_vector stdout ----
HERE [1310.1653421790038, 1330.8172301198292, 1277.2637935940652, 1210.6568270900138, 1499.470126610881] 
 [1310.1648777130713, 1330.8171481087843, 1277.2637172259465, 1210.6567863715723, 1499.4699880064272] 
DOMAIN Domain { origin: [-0.004881261667842805, -0.00489407482601417, -0.0049129845603720895], diameter: [1.0098751160568404, 1.0098751160568404, 1.0098751160568404] }
vt big [152, 48032] [-0.0033326695790912163, 4.82355321958152e-15, -0.003596491233507777, -2.6192449238942034e-16, 1.0420734412100655e-14, -0.002599800776921847, 6.0932079318093636e-15, 1.6232896042020456e-15, -2.7322900288704524e-14, -0.0012210724131814332]
locals [285.9331314400491, -24.630770968696886, 21.553815027177944, -32.53903125029487, 93.04181125954698, -198.2193991780297, -24.325566064294733, -15.555155274588747, 3.4708810892622335, 10.196277236720055]
HERE [1310.1653421790038, 1330.8172301198292, 1277.2637935940652, 1210.6568270900138, 1499.470126610881] 
 [1361.498984270484, 1381.4746658037618, 1324.4566822818865, 1258.7578479913848, 1553.7491954626844] 
thread 'fmm::test::test_fmm_vector' panicked at fmm/src/fmm.rs:570:9:
assertion failed: false
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace


failures:
    fmm::test::test_fmm_vector

test result: FAILED. 0 passed; 1 failed; 0 ignored; 0 measured; 3 filtered out; finished in 2.91s

